name: Build on Ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        use-vulkan: [ true, false ]
        os: [ ubuntu-18.04, ubuntu-20.04 ]

    runs-on: ${{ matrix.os }}
    name: "Build on ${{ matrix.os }} (Vulkan: ${{ matrix.use-vulkan }})"

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install Vulkan SDK
      if: matrix.use-vulkan
      shell: bash
      run: |
        distro_code_name=$(lsb_release -c | grep -oP "\:\s+\K\S+")
        wget -qO - https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
        sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-${distro_code_name}.list \
        https://packages.lunarg.com/vulkan/lunarg-vulkan-${distro_code_name}.list
        sudo apt update
        sudo apt install vulkan-sdk shaderc

    - name: Install system packages
      run: |
        sudo apt-get update
        sudo apt-get install git cmake libglm-dev libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libpng-dev libboost-filesystem-dev libtinyxml2-dev libarchive-dev libglew-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --parallel 4
