name: Build on Ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        use-vulkan: [ true, false ]
        os: [ ubuntu-20.04, ubuntu-22.04 ]

    runs-on: ${{ matrix.os }}
    name: "Build on ${{ matrix.os }} (Vulkan: ${{ matrix.use-vulkan }})"

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install Vulkan SDK
      if: matrix.use-vulkan
      shell: bash
      run: |
        distro_code_name="$(lsb_release -c | grep -oP "\:\s+\K\S+")"
        os_arch="$(uname -m)"
        if ! curl -s -I "https://packages.lunarg.com/vulkan/dists/{distro_code_name}/" | grep "2 404" > /dev/null; then
          wget -qO - https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
          sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-${distro_code_name}.list \
          https://packages.lunarg.com/vulkan/lunarg-vulkan-${distro_code_name}.list
          sudo apt update
          sudo apt install vulkan-sdk shaderc
        else
          curl --silent --show-error --fail -O https://sdk.lunarg.com/sdk/download/latest/linux/vulkan-sdk.tar.gz
          mkdir -p VulkanSDK
          tar -xzf vulkan-sdk.tar.gz -C VulkanSDK
          # Fix pkgconfig file.
          shaderc_pkgconfig_file="VulkanSDK/$(ls VulkanSDK)/$os_arch/lib/pkgconfig/shaderc.pc"
          prefix_path=$(realpath "VulkanSDK/$(ls VulkanSDK)/$os_arch")
          sed -i '3s;.*;prefix=\"'$prefix_path'\";' "$shaderc_pkgconfig_file"
          sed -i '5s;.*;libdir=${prefix}/lib;' "$shaderc_pkgconfig_file"
          echo "PKG_CONFIG_PATH=\"$(realpath "VulkanSDK/$(ls VulkanSDK)/$os_arch/lib/pkgconfig")\"" >> $GITHUB_ENV
        fi

    - name: Install system packages
      shell: bash
      run: |
        sudo apt-get update
        distro_code_name=$(lsb_release -c | grep -oP "\:\s+\K\S+")
        if [ "$distro_code_name" = "jammy" ]; then
          # Fix for https://askubuntu.com/questions/1417403/can-not-install-libudev-dev-on-ubuntu-22-04/1417416#1417416
          sudo apt-get install aptitude
          sudo apt-get upgrade
          sudo apt-get --with-new-pkgs upgrade
          sudo aptitude full-upgrade -y
          sudo apt-get update
          sudo apt-get upgrade
        fi
        sudo apt-get install git cmake libglm-dev libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev \
        libpng-dev libboost-filesystem-dev libtinyxml2-dev libarchive-dev libglew-dev opencl-c-headers ocl-icd-opencl-dev

    - name: Configure CMake
      shell: bash
      run: |
        if [ "${{env.PKG_CONFIG_PATH}}" != "" ]; then
          VK_LAYER_PATH=""
          source "VulkanSDK/$(ls VulkanSDK)/setup-env.sh"
          export PKG_CONFIG_PATH="${{env.PKG_CONFIG_PATH}}"
        else
          export VULKAN_SDK="/usr"
        fi
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --parallel 4
