name: Build using MSYS2

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-2022
    name: "${{ github.workflow }}"

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          base-devel
          make
          git
          curl
          wget
          mingw64/mingw-w64-x86_64-cmake
          mingw64/mingw-w64-x86_64-gcc
          mingw64/mingw-w64-x86_64-gdb
          mingw64/mingw-w64-x86_64-glm
          mingw64/mingw-w64-x86_64-libpng
          mingw64/mingw-w64-x86_64-tinyxml2
          mingw64/mingw-w64-x86_64-boost
          mingw64/mingw-w64-x86_64-libarchive
          mingw64/mingw-w64-x86_64-SDL2
          mingw64/mingw-w64-x86_64-SDL2_image
          mingw64/mingw-w64-x86_64-glew
          mingw64/mingw-w64-x86_64-vulkan-headers
          mingw64/mingw-w64-x86_64-vulkan-loader
          mingw64/mingw-w64-x86_64-vulkan-validation-layers
          mingw64/mingw-w64-x86_64-shaderc
          mingw64/mingw-w64-x86_64-opencl-headers
          mingw64/mingw-w64-x86_64-opencl-icd

    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Configure CMake
      run: cmake -B "${{github.workspace}}/build" -G "MSYS Makefiles" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build "${{github.workspace}}/build" --config ${{env.BUILD_TYPE}} --parallel 4
