name: Build using MSYS2

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { msystem: MINGW64, pkg_prefix: mingw-w64-x86_64 }
          - { msystem: UCRT64,  pkg_prefix: mingw-w64-ucrt-x86_64 }
          - { msystem: CLANG64, pkg_prefix: mingw-w64-clang-x86_64 }

    runs-on: windows-2022
    name: "${{ github.workflow }} (${{ matrix.msystem }})"

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          update: true
          install: >-
            base-devel
            make
            git
            curl
            wget
            ${{ matrix.pkg_prefix }}-cmake
            ${{ matrix.pkg_prefix }}-toolchain
            ${{ matrix.pkg_prefix }}-glm
            ${{ matrix.pkg_prefix }}-libpng
            ${{ matrix.pkg_prefix }}-tinyxml2
            ${{ matrix.pkg_prefix }}-boost
            ${{ matrix.pkg_prefix }}-libarchive
            ${{ matrix.pkg_prefix }}-SDL2
            ${{ matrix.pkg_prefix }}-SDL2_image
            ${{ matrix.pkg_prefix }}-glew
            ${{ matrix.pkg_prefix }}-glfw
            ${{ matrix.pkg_prefix }}-vulkan-headers
            ${{ matrix.pkg_prefix }}-vulkan-loader
            ${{ matrix.pkg_prefix }}-vulkan-validation-layers
            ${{ matrix.pkg_prefix }}-shaderc
            ${{ matrix.pkg_prefix }}-directx-headers
            ${{ matrix.pkg_prefix }}-opencl-headers
            ${{ matrix.pkg_prefix }}-opencl-icd

      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Configure CMake
        run: cmake -B "${{github.workspace}}/build" -G "MSYS Makefiles" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DSUPPORT_D3D12=ON

      - name: Build
        run: cmake --build "${{github.workspace}}/build" --config ${{env.BUILD_TYPE}} --parallel 4
